### ISSUE TITLE
Records that goes beyond the last three months?

### ISSUE THREAD

**Issue by kchu25** [wickles/crypto-tools#2]
The call _accountAPI.get_ledger_record_ only get you as far as the last three months' records. This shows in the example file: https://github.com/okcoin-com/V3-Open-API-SDK/blob/bca587cf817d9ee0df417d83bbdc0201029e0bad/okcoin-python-sdk-api/example.py

Is there a way to get records the covers beyond the last three months?

**Comment by wickles** [comment]
I suspect there should be a way to get the full records but I have not had a chance to look into it yet. If you work it out please do drop a hint or a PR!

**Comment by kchu25** [comment]
I see. Thanks!
